import { restGet, restInsert, restPatch, restDelete, TokenProvider } from '../lib/rest'
import { formatAddressFromJson } from '../lib/address'
import { supabase } from '../lib/supabaseClient'
type Profile={id:string;clerk_user_id:string;email?:string;name?:string;avatar_url?:string;role?:string}
export async function getProfileByClerkId(clerkId:string, tokenProvider?: TokenProvider):Promise<Profile|null>{
  const rows=await restGet('profiles_api',{select:'*',clerk_user_id:`eq.${clerkId}`}, tokenProvider)
  return Array.isArray(rows)&&rows.length?rows[0]:null
}
export async function upsertProfile(p:Profile, tokenProvider?: TokenProvider):Promise<Profile>{
  const existing=await getProfileByClerkId(p.clerk_user_id, tokenProvider)
  if(!existing){
    // Don't pass empty id when creating new profile - let DB generate UUID
    const { id, ...profileData } = p;
    const rows=await restInsert('profiles_api', profileData, tokenProvider);
    return rows[0];
  }
  const rows=await restPatch('profiles_api',{id:`eq.${existing.id}`},p, tokenProvider);return rows[0]
}
type PropertyInsert={name:string;address_jsonb:any;property_type:string;unit?:string;bedrooms?:number;bathrooms?:number}
export async function insertProperty(payload:PropertyInsert, tokenProvider?: TokenProvider){
  const address=formatAddressFromJson(payload.address_jsonb,payload.unit)
  
  // Create property with explicit property code generation
  const propertyData = {
    ...payload,
    address,
    // These will be set by database function or trigger, but we can specify defaults
    allow_tenant_signup: true,
    // property_code will be auto-generated by trigger or function
  }
  
  const rows=await restInsert('properties', propertyData, tokenProvider)
  const newProperty = rows[0]
  
  // If property code wasn't generated, we need to update it
  // This is a fallback in case the database trigger isn't set up
  if (!newProperty.property_code) {
    console.log('⚠️ Property created without code, attempting to generate one...')
    try {
      // Call the database function to generate a code
      const { data: codeData, error } = await supabase.rpc('generate_property_code')
      if (error) throw error
      
      if (codeData) {
        const updateRows = await restPatch('properties', 
          { id: `eq.${newProperty.id}` }, 
          { 
            property_code: codeData,
            code_expires_at: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(), // 90 days
            allow_tenant_signup: true 
          }, 
          tokenProvider
        )
        console.log('✅ Property code generated and updated:', codeData)
        return updateRows[0]
      }
    } catch (error) {
      console.error('Failed to generate property code:', error)
    }
  }
  
  return newProperty
}
export async function getUserProperties(tokenProvider?: TokenProvider){
  const rows=await restGet('properties',{select:'*',order:'created_at.desc'}, tokenProvider)
  return rows||[]
}
export async function insertPropertyAreas(areas:any[], tokenProvider?: TokenProvider){
  const rows=await restInsert('property_areas',areas, tokenProvider)
  return rows
}
export async function deleteProperty(propertyId: string, tokenProvider?: TokenProvider) {
  return await restDelete('properties', {id: `eq.${propertyId}`}, tokenProvider);
}
